name: Docker

on:
  push:
    branches: ['master']

jobs:
  build-dh:
    name: Build & Push (Docker Hub)
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hbjy/linkd:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-gh:
    name: Build & Push (GitHub Container Registry)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: hbjydev/linkd/linkd
          tag_with_ref: true
